src/Arcus.Observability.Telemetry.Serilog/VersionEnricher.cs
=> FIX: use EntryAssembly to retrieve version in enricher

docs/features/telemetry-enrichment.md, src/Arcus.Observability.Telemetry.Serilog.Enrichers/ApplicationEnricher.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LoggerEnrichmentConfigurationExtensions.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/KubernetesEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/VersionEnricherTests.cs
Closes https://github.com/arcus-azure/arcus.observability/issues/38
=> Feature - provide extensions to add Serilog enrichers

src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CustomTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/OperationContextConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/TraceTelemetryConverter.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/OperationContextConverterTests.cs
Automatically assign Context.Operation.Id with correlation info
Relates to https://github.com/arcus-azure/arcus.observability/issues/69
=> Automatically assign Context.Operation.Id with correlation info

src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CustomTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/EventTelemetryConverter.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
Closes https://github.com/arcus-azure/arcus.observability/issues/83
=> Feature - remove 'EventDescription' log property from the telemetry

src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LogEventPropertyValueExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/ApplicationInsightsTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CustomTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/ExceptionTelemetryConverter.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ExceptionTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
=> Track exceptions to Azure Application Insights

docs/v0.2.0/features/correlation.md
Fixed a small typo and fixed layout of code examples.
=> Fixed typo and code layout

src/Arcus.Observability.Telemetry.Core/ContextProperties.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/MetricTelemetryConverter.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
=> Feature - add timestamp to metric telemetry tracking

src/Arcus.Observability.Telemetry.Core/ContextProperties.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CustomTelemetryConverter.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
* Uses `Context` instead of `EventDescription` in the message template
* Deprecate the use of `ContextProperties.EventTracking.EventContext`.
* Update log event > telemtry conversion with this deprecation to use both properties to enrich the telemetry context.
Closes #114
=> Feature - use 'Context' instead of 'EventDescription' as property name

docs/preview/guidance/use-with-dotnet-and-functions.md, src/Arcus.Observability.Telemetry.AzureFunctions/Arcus.Observability.Telemetry.AzureFunctions.csproj, src/Arcus.Observability.Telemetry.AzureFunctions/Extensions/ILoggerBuilderExtensions.cs, src/Arcus.Observability.Tests.Unit/Arcus.Observability.Tests.Unit.csproj, src/Arcus.Observability.Tests.Unit/Telemetry/AzureFunctions/Fixture/FunctionFileLoggerProvider.cs, src/Arcus.Observability.Tests.Unit/Telemetry/AzureFunctions/Fixture/HostFileLoggerProvider.cs, src/Arcus.Observability.Tests.Unit/Telemetry/AzureFunctions/Fixture/TestLoggerProvider.cs, src/Arcus.Observability.Tests.Unit/Telemetry/AzureFunctions/ILoggerBuilderExtensionsTests.cs, src/Arcus.Observability.sln
Add logger extension so one can use the 'old' `.AddSerilog` extension when building an Azure Functions application.
The extension makes sure that existing logger providers (except the specific functions' ones) are removed from the registered logger providers.
Closes #118
=> Feature - clear logger providers except functions extension

docs/preview/features/telemetry-enrichment.md, src/Arcus.Observability.Telemetry.Serilog.Enrichers/ApplicationEnricher.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/CorrelationInfoEnricher.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LoggerEnrichmentConfigurationExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/KubernetesEnricher.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/VersionEnricher.cs, src/Arcus.Observability.Tests.Core/Arcus.Observability.Tests.Core.csproj, src/Arcus.Observability.Tests.Core/InMemoryLogSink.cs, src/Arcus.Observability.Tests.Integration/Serilog/KubernetesEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Blanks.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/CorrelationInfoEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/KubernetesEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/VersionEnricherTests.cs
The Serilog property names were hard-coded in the initial version but right now we should think about making them configurable so the naming conventions in a certain project about the log properties can be uphold.
Closes #141
=> Feature - make Serilog property names of the enrichers configurable

docs/preview/features/telemetry-enrichment.md, src/Arcus.Observability.Telemetry.Serilog.Enrichers/AssemblyAppVersion.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LoggerEnrichmentConfigurationExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/IAppVersion.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/VersionEnricher.cs, src/Arcus.Observability.Tests.Unit/Serilog/VersionEnricherTests.cs
Provides a custom `IAppVersion` interface to inject your own custom application version while enriching the log events with the `VersionEnricher`. Existing functionality to use the current runtime version of the assembly is moved to an `AssemblyAppVersion` instance and is still the default.
Closes #143
=> Feature - inject custom application version in Serilog version enricher

docs/preview/features/telemetry-enrichment.md, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LoggerEnrichmentConfigurationExtensions.cs, src/Arcus.Observability.Tests.Unit/Serilog/VersionEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/DummyAppVersion.cs, src/Arcus.Observability.Tests.Unit/Telemetry/IServiceCollectionExtensionsTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/StubAppVersion.cs
Provide the capability to register the `IAppVersion` in the application services instead of providing the instance yourself. This also includes the dev-friendly registration of this service.
Relates to #143
=> Feature - register the IAppVersion as service

docs/preview/features/telemetry-enrichment.md, src/Arcus.Observability.Telemetry.Serilog.Enrichers/AssemblyAppVersion.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Observability.Tests.Unit/Arcus.Observability.Tests.Unit.csproj, src/Arcus.Observability.Tests.Unit/Serilog/AssemblyAppVersionTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/IServiceCollectionExtensionsTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/VersionEnricherTests.cs
Provides the capability to pass along a custom type to the `AssemblyAppVersion` so we're not limited or restricted to the `Assembly.GetEntryAssembly` call and the consumer is in control _in what_ `Assembly`  the Serilog `VersionEnricher` should look for the application version. Useful for Azure Functions.
Closes #146
=> Feature - provide consumer type to AssemblyAppVersion

docs/preview/features/writing-different-telemetry-types.md, src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Sql/Arcus.Observability.Telemetry.Sql.csproj, src/Arcus.Observability.Telemetry.Sql/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Tests.Unit/Arcus.Observability.Tests.Unit.csproj, src/Arcus.Observability.sln
Move the SQL package together with the related dependency tracking extensions to a seperate project.
Closes #131
=> Feature - move SQL dependency tracking to sep project

src/Arcus.Observability.Telemetry.Serilog.Enrichers/KubernetesEnricher.cs, src/Arcus.Observability.Tests.Integration/Arcus.Observability.Tests.Integration.csproj, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/AzureSearchDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/BlobStorageDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/CosmosSqlDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/CustomDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventHubsTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ExceptionTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/HttpDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/IoTHubTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/MetricTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/RequestTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ServiceBusDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/SqlDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/TableStorageDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/TraceTests.cs
Since there's a new version released of the Azure SDK Application Insights package to retrieve also the custom dimensions of tracked events, we can finally test our Serilog enrichers thorougly.
Clloses #93
=> Test - use custom dimensions in integration tests

src/Arcus.Observability.Telemetry.Core/AssemblyAppVersion.cs, src/Arcus.Observability.Telemetry.Core/IAppVersion.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/VersionEnricher.cs, src/Arcus.Observability.Tests.Unit/Serilog/AssemblyAppVersionTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/VersionEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/DummyAppVersion.cs, src/Arcus.Observability.Tests.Unit/Telemetry/IServiceCollectionExtensionsTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/StubAppVersion.cs
Moves the `IAppVersion` and `AssemblyAppVersion` types to the telemtry Core project.
Closes #145
=> Feature - move IAppVersion & AssemblyAppVersion to Core

src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
Use Microsoft log level `Warning` to log our telemetry core log events (for Application Insights) so Serilog filtering on the `Warning` log level will not filter out our Application Insights-specific telemetry logs.
Closes #154
=> Fix - use warning logs instead of information for telemtry core

docs/preview/features/telemetry-enrichment.md, src/Arcus.Observability.Correlation/DefaultCorrelationInfoAccessor.cs, src/Arcus.Observability.Correlation/DefaultCorrelationInfoAccessorT.cs, src/Arcus.Observability.Correlation/IServiceCollectionExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LoggerEnrichmentConfigurationExtensions.cs, src/Arcus.Observability.Tests.Unit/Correlation/DefaultCorrelationInfoAccessorTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/CorrelationInfoEnricherTests.cs
We first uses a different correlation information for each asyhchronous operation, but this is actually wrong as we already use a scoped service for this. We should consider not using the static value for the default correlation info accessor as this would be the same accross requests. So we should create a new accessor for each request instead.
Closes #159
=> Fix - set correlation info throughout async operations

docs/preview/features/writing-different-telemetry-types.md, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/AzureKeyVaultDependencyTests.cs, src/Arcus.Observability.Tests.Unit/InvalidAzureKeyVaultSecretsNames.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs, src/Arcus.Observability.Tests.Unit/ValidAzureKeyVaultSecretNames.cs
Adds a new telemetry extension to track Azure Key Vault dependencies in Application Insights.
This one can be used, later, within the tracking of the secret store (which now uses the general dependency tracking).
Closes #157
=> Feature - track Azure Key Vault dependency

docs/features/sinks/azure-application-insights.md, docs/preview/features/sinks/azure-application-insights.md
Added some guidance in the Q&A section of the documentation on how to use / configure the logger.
Closes #168
=> Add guidance on where to configure the logger

docs/guidance/use-with-dotnet-and-functions.md
The latest FunctionsHostBuilder has a method GetContext that can give
you access to the Configuration.  No need to build a ServiceProvider to
require the configuration anymore.
=> Improve guidance documentation

src/Arcus.Observability.Telemetry.AspNetCore/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Core/FormatSpecifiers.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Extensions/LoggerSinkConfigurationExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/AzureKeyVaultDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/AzureSearchDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/BlobStorageDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/CosmosSqlDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/CustomDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventHubsTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ServiceBusDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/SqlDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/TableStorageDependencyTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/LogEventPropertyValueExtensionsTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
When dependencies are tracked, the starttime of the dependency is converted to a string using the InvariantCulture format provider.  However, this provider only converts the datetime to a string with a precision up to the second.
There doesn't seem to be any built-in format provider that converts dates to strings with millisecond precision, so we've specified our own.
closes #180
=> Log starttime of dependencies up to the millisecond

docs/preview/features/sinks/azure-application-insights.md, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Configuration/ApplicationInsightsSinkExceptionOptions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Configuration/ApplicationInsightsSinkOptions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/ApplicationInsightsTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/ExceptionTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Extensions/LoggerSinkConfigurationExtensions.cs, src/Arcus.Observability.Tests.Integration/Fixture/TestException.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ExceptionTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkExceptionOptionsTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/Sinks/ApplicationInsights/LoggerConfigurationExtensionsTests.cs
Include public properties when tracking exceptions to Azure Application Insights. This means that any custom and existing (base) properties will be included as `customDimensions` in the exception tracking entries in Application Insights.
Closes #184
=> feat: track exceptions more thoroughly

docs/v2.1/guidance/use-with-dotnet-and-functions.md
=> fix: small typo in use-with-dotnet-and-functions.md

src/Arcus.Observability.Telemetry.AspNetCore/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
Adds some additional guard checks to guard against negative time durations, response status codes outsides bounds of the enumeration, and missing blank checks for textual information.
Closes #201
=> feat: improve guard checks on telemetry logging

docs/preview/features/writing-different-telemetry-types.md, src/Arcus.Observability.Telemetry.AspNetCore/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Core/ContextProperties.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/IReadOnlyDictionaryExtensions.cs, src/Arcus.Observability.Telemetry.Core/FormatSpecifiers.cs, src/Arcus.Observability.Telemetry.Core/Logging/DependencyLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Logging/EventLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Logging/MetricLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Logging/RequestLogEntry.cs, src/Arcus.Observability.Telemetry.Core/MessageFormats.cs, src/Arcus.Observability.Telemetry.Core/MessagePrefixes.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LogEventPropertyValueExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CustomTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/Dependencies/CustomDependencyTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/Dependencies/HttpDependencyTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/Dependencies/SqlDependencyTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/DependencyTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/EventTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/MetricTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/RequestTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/TraceTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Extensions/IDictionaryExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Extensions/LogEventPropertyExtensions.cs, src/Arcus.Observability.Tests.Unit/Arcus.Observability.Tests.Unit.csproj, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/Extensions/LogEventPropertyValueExtensionsTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
Change the way we log telemetry output by creating separate models that gets logged in one go without the 'sentence-like' formatting; which is not serializable.
Closes #205
=> feat: log telemetry as structured value models for Serilog formatting

src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Core/Logging/DependencyLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Logging/EventLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Logging/MetricLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Logging/RequestLogEntry.cs, src/Arcus.Observability.Telemetry.Core/TelemetryType.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LogEventPropertyValueExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Filters/TelemetryTypeFilter.cs, src/Arcus.Observability.Tests.Integration/Arcus.Observability.Tests.Integration.csproj, src/Arcus.Observability.Tests.Integration/Serilog/TelemetryTypeFilterTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/Extensions/LogEventPropertyValueExtensionsTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/TelemetryTypeFilterTests.cs
Updates the `TelemetryTypeFilter` so it can be used with the new telemetry log format + outside Azure Application Insights sinks.
Closes #206
=> feat: revisit telemetry type filter usage outside Azure Application Insights Serilog sink

docs/preview/features/correlation.md, src/Arcus.Observability.Correlation/CorrelationInfo.cs, src/Arcus.Observability.Telemetry.Core/ContextProperties.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Configuration/CorrelationInfoEnricherOptions.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/CorrelationInfoEnricher.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LoggerEnrichmentConfigurationExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/OperationContextConverter.cs, src/Arcus.Observability.Tests.Integration/AssertX.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ExceptionTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/Enrichers/ApplicationEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/Enrichers/Configuration/CorrelationInfoEnricherOptionsTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/Enrichers/CorrelationInfoEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/Enrichers/KubernetesEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/Enrichers/TestCorrelationInfoEnricher.cs, src/Arcus.Observability.Tests.Unit/Serilog/Enrichers/VersionEnricherTests.cs
Adds the operation parent ID correlation information to our `CorrelatinoInfo` model so we can also include it in Serilog enrichment.
Relates to https://github.com/arcus-azure/arcus.webapi/issues/233
=> feat: add operation parent ID to correlation info

src/Arcus.Observability.Telemetry.AspNetCore/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Core/Logging/RequestLogEntry.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CloudContextConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CustomTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/OperationContextConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/RequestTelemetryConverter.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/AzureKeyVaultDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/AzureSearchDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/BlobStorageDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/CosmosSqlDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/CustomDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventHubsTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/IoTHubTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/RequestTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ServiceBusDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/SqlDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/TableStorageDependencyTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/TelemetryTypeFilterTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/OperationContextConverterTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
- Requests are now logged with an operation name so they don't show in Application Insights as '<Empty>'. For example: 
After discussion with @stijnmoreels we decided to add 2 overloads to be able to specify a custom operataion name as well. 
- Names have been added to all dependancies so that they don't show up in Application Insights 'n/a'. For example:
=> feat: Provide dependency names for dependencies & requests

docs/README.md
Typo in 'syntax highlighting'.
=> docs: typo in 'syntax highlighting'

src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LogEventPropertyValueExtensions.cs, src/Arcus.Observability.Tests.Unit/Fixture/Order.cs, src/Arcus.Observability.Tests.Unit/Fixture/OrderGenerator.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
Use the Serilog `ScalarValue` (represents simple value) when serializing the Serilog log property value to a `string` representation. This fix will make sure that we retrieve the original value (unescaped). This will make JSON values represents as their original values instead of escaped quotes (`\"`).
Closes #256
=> fix: use serilog scalar value when serializing string values

docs/preview/02-Features/sinks/azure-application-insights.md, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Configuration/ApplicationInsightsSinkOptions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Configuration/ApplicationInsightsSinkRequestOptions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/ApplicationInsightsTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/RequestTelemetryConverter.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/RequestTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs, src/Arcus.Observability.Tests.Unit/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkRequestOptionsTests.cs
Adds an configurable option to generate the telemetry request ID when tracking requests to Azure Application Insights.
Closes #248
=> feat: generate request telemetry id

build/ci-build.yml, build/nuget-release.yml, build/variables/build.yml, src/Arcus.Observability.Correlation/Arcus.Observability.Correlation.csproj, src/Arcus.Observability.Telemetry.AspNetCore/Arcus.Observability.Telemetry.AspNetCore.csproj, src/Arcus.Observability.Telemetry.AzureFunctions/Arcus.Observability.Telemetry.AzureFunctions.csproj, src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj, src/Arcus.Observability.Telemetry.IoT/Arcus.Observability.Telemetry.IoT.csproj, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Arcus.Observability.Telemetry.Serilog.Enrichers.csproj, src/Arcus.Observability.Telemetry.Serilog.Filters/Arcus.Observability.Telemetry.Serilog.Filters.csproj, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights.csproj, src/Arcus.Observability.Telemetry.Sql/Arcus.Observability.Telemetry.Sql.csproj, src/Arcus.Observability.Tests.Core/Arcus.Observability.Tests.Core.csproj, src/Arcus.Observability.Tests.Integration/Arcus.Observability.Tests.Integration.csproj, src/Arcus.Observability.Tests.Unit/Arcus.Observability.Tests.Unit.csproj
Upgrades towards .NET 6 while keeping .NET Core backwards compability.
Relates to https://github.com/arcus-azure/arcus/issues/106
=> chore: upgrade to net6.0

src/Arcus.Observability.Telemetry.Core/Logging/RequestSourceSystem.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/RequestTelemetryConverter.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Extensions/LogEventPropertyExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ServiceBusRequestTests.cs
Complete the connection between Serilog logging <> Application Insights tracking of Azure Service Bus request.
Closes #244
Closes #245
=> feat: track az servicebus in app insights

docs/preview/02-Features/writing-different-telemetry-types.md, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Core/RequestMeasurement.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
Use a new `RequestMeasurement` object to measure requests.
Closes #268
=> feat: add request measurement for requests

src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights.csproj
Upgrades Application Insights NuGet package to a non-deprecated version.
Closes #271
=> chore: update appinsights nuget package

docs/preview/02-Features/writing-different-telemetry-types.md, src/Arcus.Observability.Telemetry.AspNetCore/Arcus.Observability.Telemetry.AspNetCore.csproj, src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj, src/Arcus.Observability.Telemetry.Core/DependencyMeasurement.cs, src/Arcus.Observability.Telemetry.Core/DurationMeasurement.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.IoT/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Telemetry.Sql/Arcus.Observability.Telemetry.Sql.csproj, src/Arcus.Observability.Telemetry.Sql/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Tests.Unit/Extensions/TestLoggerExtensions.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
Rename `RequestMeasurement` to `DurationMeasurement` and use that instead of `DependencyMeasurement`.
Closes #283
=> feat: add duration measurement io dependency measurement

.github/renovate.json
Seems that the wildcard doesn't work, let's try this one.
=> fix: discard `/docs` folder

src/Arcus.Observability.Correlation/Arcus.Observability.Correlation.csproj, src/Arcus.Observability.Telemetry.AspNetCore/Arcus.Observability.Telemetry.AspNetCore.csproj, src/Arcus.Observability.Telemetry.AzureFunctions/Arcus.Observability.Telemetry.AzureFunctions.csproj, src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj, src/Arcus.Observability.Telemetry.IoT/Arcus.Observability.Telemetry.IoT.csproj, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Arcus.Observability.Telemetry.Serilog.Enrichers.csproj, src/Arcus.Observability.Telemetry.Serilog.Filters/Arcus.Observability.Telemetry.Serilog.Filters.csproj, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights.csproj, src/Arcus.Observability.Telemetry.Sql/Arcus.Observability.Telemetry.Sql.csproj, src/Arcus.Observability.Tests.Integration/Arcus.Observability.Tests.Integration.csproj
Correct the NuGet dependencies to start from the current minor and take every minor that follows till the next major.
Includes reverts of Renovate on IoT and Serilog.Enrichers.
Closes #330
=> chore: correct nuget dependencies

src/Arcus.Observability.Telemetry.AzureFunctions/Extensions/ILoggerBuilderExtensions.cs, src/Arcus.Observability.Tests.Unit/Correlation/DefaultCorrelationInfoAccessorTests.cs
This method is not correctly implemented and calling this method has the side-effect that logging to Application Insights is not working correctly.
It is advised to not longer use this method.
See also #336
=> chore: Mark ClearProvidersExceptFunctionProviders as obsolete

.github/workflows/codeql-analysis.yml
Add default CodeQL code analysis file.
Relates to https://github.com/arcus-azure/arcus/discussions/195
=> chore: add CodeQL code analysis

src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/AzureSearchDependencyTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
Adds the capability to add a dependency ID when tracking Azure Search dependencies.
Related to #243
=> feat: add dependency id to az search

src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ServiceBusDependencyTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
Adds the capability to add a dependency ID when tracking Azure Service Bus queue dependencies.
Related to #243
=> feat: add dependency id to az servicebus queue tracking

docs/preview/03-Guidance/use-with-dotnet-and-functions.md, docs/versioned_docs/version-v2.4/03-Guidance/use-with-dotnet-and-functions.md
Remove the 'Clear logging providers' extension call from the preview and recently published docs (v2.4).
This call is deprecated and should no longer be added to the 'recommanded' approach.
=> docs: remove 'clear logging providers' from preview & published docs

src/Arcus.Observability.Correlation/Arcus.Observability.Correlation.csproj, src/Arcus.Observability.Telemetry.AspNetCore/Arcus.Observability.Telemetry.AspNetCore.csproj, src/Arcus.Observability.Telemetry.AzureFunctions/Arcus.Observability.Telemetry.AzureFunctions.csproj, src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj, src/Arcus.Observability.Telemetry.IoT/Arcus.Observability.Telemetry.IoT.csproj, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Arcus.Observability.Telemetry.Serilog.Enrichers.csproj, src/Arcus.Observability.Telemetry.Serilog.Filters/Arcus.Observability.Telemetry.Serilog.Filters.csproj, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights.csproj, src/Arcus.Observability.Telemetry.Sql/Arcus.Observability.Telemetry.Sql.csproj
Adds the GitHub README file to the NuGet package generation of the projects.
Adds feature docs project URL instead of GitHub URL to NuGet package.
Relates to https://github.com/arcus-azure/arcus/issues/209
Relates to https://github.com/arcus-azure/arcus/issues/208
=> chore: add readme to nuget packages + feature docs project URL

src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerTableStorageDependencyExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/TableStorageDependencyTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureTableStorageDependencyTests.cs
Adds dependency ID to Azure Table storage dependency tracking.
Relates to https://github.com/arcus-azure/arcus.observability/issues/243
=> feat: add dependency id to az tabe storage dep tracking

src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerSqlDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Sql/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Tests.Integration/Arcus.Observability.Tests.Integration.csproj, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/SqlDependencyTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/SqlDependencyLoggingTests.cs
Adds dependency ID to SQL dependency tracking.
Closes #286
=> feat: add dependency id to sql dep tracking

build/nuget-release.yml
We use the wrong local template in the NuGet release.
=> fix: nuget docker tests template ref

src/Arcus.Observability.Correlation/CorrelationInfoOptions.cs, src/Arcus.Observability.Correlation/CorrelationInfoUpstreamServiceOptions.cs, src/Arcus.Observability.Tests.Unit/Correlation/CorrelationInfoOptionsTests.cs
This will also make things a better streamlined as the operation parent ID was already in the Serilog correlation enrichers but not in the correlation model itself.
Currently, only the HTTP correlation properties has this upstream service, but with this in place, we wouldn't need that anymore.
Related to https://github.com/arcus-azure/arcus.templates/issues/575
=> feat: add upstream service correlation options

src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerSqlDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Sql/Extensions/ILoggerExtensions.cs
Deprecate the SQL dependency tracking overloads without the SQL command but uses the table and operation name instead.
Follow-up of #286
=> chore: deprecated sql dep tracking overloads w/o sql command

src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CustomTelemetryConverter.cs
We only need to remove the call to add the telemetry properties from the `ContextProperties.EventTracking.EventContext` Serilog log property, and since we moved it to `ContextProperties.TelemetryContext`, we can still use this method.
=> chore: remove unnecessary deprecation

src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusDependencyExtensions.cs
Fix the deprecation messages of the Azure Service Bus queue/topic/general dependency tracking extensions.
Closes #417
=> fix: use correct deprecation az servicebus messages

src/Arcus.Observability.Tests.Unit/Telemetry/AzureFunctions/Fixture/ApplicationInsightsLoggerProvider.cs, src/Arcus.Observability.Tests.Unit/Telemetry/AzureFunctions/ILoggerBuilderExtensionsTests.cs
Add unit test for `.RemoveMicrosoftApplicationInsightsLoggerProvider` with dummy type.
Closes #433
=> test: add unit test for remove micro app insights extension

docs/preview/03-Features/writing-different-telemetry-types.md, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerGeneralExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ExceptionTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/TraceTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/GeneralLoggingTests.cs
Add telemetry context to general traces/exceptions tracking.
Closes #430
=> feat: add telemetry context tracking for general traces/exceptions

src/Arcus.Observability.Telemetry.Core/ContextProperties.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusDependencyExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ServiceBusDependencyTests.cs, src/Arcus.Observability.Tests.Unit/Extensions/TestLoggerExtensions.cs, src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureServiceBusDependencyLoggingTests.cs
We should use the Azure ServiceBus entity name as the telemetry dependency target name when tracking Azure Service Bus dependencies because otherwise the request/dependency will not recognize the relationship as the same component/resource.
=>  (❗) fix: servicebus entityname as dependency targetname

docs/preview/03-Features/writing-different-telemetry-types.md
Use new overload for SQL dependency tracking that uses a pseudo SQL command instead of a fixed SQL table in the feature documentation page.
Closes #423
=> docs: use new sql dependency approach

docs/preview/03-Features/writing-different-telemetry-types.md, src/Arcus.Observability.Telemetry.Core/ContextProperties.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerEventHubsRequestExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerGeneralRequestExtensions.cs, src/Arcus.Observability.Telemetry.Core/Logging/RequestLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Logging/RequestSourceSystem.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/RequestTelemetryConverter.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/CustomRequestTests.cs, src/Arcus.Observability.Tests.Unit/Extensions/TestLoggerExtensions.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/CustomRequestLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/EventHubsRequestLoggingTests.cs
Adds extensions to track custom requests (like we can track custom dependencies) to let users make use of Observability outside provided systems we provide request tracking (API, Service Bus, EventHubs).
Closes #438
=> feat: track custom request

docs/package-lock.json, docs/preview/03-Features/writing-different-telemetry-types.md, src/Arcus.Observability.Telemetry.AzureFunctions/Arcus.Observability.Telemetry.AzureFunctions.csproj, src/Arcus.Observability.Telemetry.AzureFunctions/Extensions/ILoggerHttpRequestDataExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerRequestExtensions.cs, src/Arcus.Observability.Tests.Integration/Arcus.Observability.Tests.Integration.csproj, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/HttpRequestDataTests.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/RequestTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/HttpRequestDataLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/HttpRequestLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/MetricLoggingTests.cs
Adds HTTP request tracking for isolated Azure Functions HTTP trigger's `HttpRequestData`.
Closes #443
=> feat: track http request data in http trigger

src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LogEventPropertyValueExtensions.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/GeneralLoggingTests.cs
Reason why the Azure Functions didn't always tracked the request, was that the operation parent ID was `null` in the initial call and this `null` wasn't checked when parsing the Serilog values to typed variants.
=> (❗) fix: null-check on scalar value

docs/preview/03-Features/writing-different-telemetry-types.md, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerSqlDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Sql/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/SqlDependencyTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/SqlDependencyLoggingTests.cs
Make the dependency name unique by adding a functional description of the operation.
Closes #419
=> (❗) fix: add operation name to sql dependency tracking

src/Arcus.Observability.Telemetry.AzureFunctions/Extensions/ILoggerBuilderExtensions.cs, src/Arcus.Observability.Tests.Unit/Telemetry/AzureFunctions/ILoggerBuilderExtensionsTests.cs
The newest Azure Functions SDK doesn't have this logger provider anymore in the default registered logger providers, so we should remove the invalid operation throwal.
Closes #441
=> (❗) chore: update w/o invalid operation exception throwal

docs/preview/02-Guidance/Service-to-service Correlation/use-service-to-service-correlation-in-web-api.md
User-guide for Web API service-to-service correlation had some invalid correlation ID's in the example
=> (❗) docs: fix webapi userguide correlation ids

docs/preview/02-Guidance/Service-to-service Correlation/index.md, docs/preview/02-Guidance/Service-to-service Correlation/use-service-to-service-correlation-in-service-bus.md, docs/versioned_docs/version-v2.6.0/02-Guidance/Service-to-service Correlation/index.md, docs/versioned_docs/version-v2.6.0/02-Guidance/Service-to-service Correlation/use-service-to-service-correlation-in-service-bus.md
We have released Arcus Messaging v1.3 which includes the necessary functionality that is needed to understand the Azure Service Bus service-to-service correlation user guide.
This means we can add the user guide (which already was in preview) to the published v2.6 feature docs.
=> docs: add servicebus service-to-service correlation userguide to v2.6 feature docs

docs/preview/03-Features/telemetry-enrichment.md, src/Arcus.Observability.Telemetry.Core/DefaultAppName.cs, src/Arcus.Observability.Telemetry.Core/IAppName.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LoggerEnrichmentConfigurationExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Configuration/ApplicationTelemetryInitializer.cs, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Observability.Tests.Unit/Serilog/Enrichers/ApplicationEnricherTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/IServiceCollectionExtensionsTests.cs
Extract application/component name so that both Arcus and Microsoft functionality can benefit from this.
Closes https://github.com/arcus-azure/arcus.observability/issues/470
=> feat: add re-usable application name

src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights.csproj, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Extensions/ILoggingBuilderExtensions.cs, src/Arcus.Observability.Tests.Unit/Serilog/ILoggingBuilderExtensionsTests.cs
Add `logging.AddSerilog` overload that can take in an `IServiceProvider` so that we can add our correlation enricher more easily in in-process Azure Functions environments.
Closes #481
=> feat: add 'AddSerilog' extension overload with 'IServiceProvider'

docs/preview/03-Features/sinks/azure-application-insights.md, src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Extensions/LoggerSinkConfigurationExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkExtensionTests.cs, src/Arcus.Observability.Tests.Runtimes.AzureFunction/Arcus.Observability.Tests.Runtimes.AzureFunction.csproj, src/Arcus.Observability.Tests.Runtimes.AzureFunction/Startup.cs, src/Arcus.Observability.Tests.Unit/Serilog/Sinks/ApplicationInsights/LoggerConfigurationExtensionsTests.cs
Assign the connection string to the previously registered Microsoft `TelemetryClient` right from the Azure Application Insights Serilog sink.
Closes #471
=> feat: assign telemetry client in serilog sink

docs/preview/03-Features/writing-different-telemetry-types.md
Add link to possible Azure Service Bus cloud suffixes in the Azure Service Bus request tracking feature documentation.
Closes #267
=> docs: add servicebus cloud suffixes in service bus request tracking feature docs

docs/preview/03-Features/writing-different-telemetry-types.md, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerIotHubDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Iot/IotHubConnectionStringParser.cs, src/Arcus.Observability.Telemetry.Core/Iot/IotHubConnectionStringParserResult.cs, src/Arcus.Observability.Telemetry.IoT/Extensions/ILoggerExtensions.cs, src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/IoTHubTests.cs, src/Arcus.Observability.Tests.Unit/Iot/IotHubConnectionStringParserTests.cs
Deprecate the `Arcus.Observability.Telemetry.IoT` functionality in favor of our own IoT Hub connection string parsing in the `.Core` project.
Closes #507
=> feat: deprecate iot hub project in favor of dedicated parsing

src/Arcus.Observability.Tests.Unit/Correlation/DefaultCorrelationInfoAccessorTests.cs
Improve asynchronous default correlation unit tests.
Closes #344
=> test: improve default correlation unit tests

docs/preview/02-Guidance/Service-to-service Correlation/use-service-to-service-correlation-in-service-bus.md, docs/versioned_docs/version-v2.6.0/02-Guidance/Service-to-service Correlation/use-service-to-service-correlation-in-service-bus.md
Use `BinaryData` correctly when sending Azure Service Bus messages in the service-to-service correlation user guide.
=> docs: fix correct az servicebus message sending usage

src/Arcus.Observability.Telemetry.AzureFunctions/Extensions/ILoggerHttpRequestDataExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerAzureKeyVaultDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerBlobStorageDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerEventExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerHttpDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerIotHubDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerMetricExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerRequestExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerSqlDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerTableStorageDependencyExtensions.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureBlobStorageDependencyLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureKeyVaultDependencyLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureTableStorageDependencyTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/HttpDependencyLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/HttpRequestDataLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/HttpRequestLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/IoTHubDependencyLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/MetricLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/SecurityEventLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/SqlDependencyLoggingTests.cs
Fixes the first set of telemetry extensions w/ a telemetry context that does not alter the original passed-in context. Split in two parts as there are a lot of extensions/tests to be changed.
Relates to #545
=> fix: do not alter original telemetry context pt.1

src/Arcus.Observability.Telemetry.AspNetCore/Extensions/ILoggerHttpDependencyExtensions.cs, src/Arcus.Observability.Telemetry.AspNetCore/Extensions/ILoggerRequestExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerAzureSearchDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerCosmosSqlDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerCustomDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerEventExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerEventHubsDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerEventHubsRequestExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerGeneralRequestExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusRequestExtensions.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureSearchDependencyLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureServiceBusDependencyLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureServiceBusRequestLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/CosmosSqlDependencyLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/CustomDependencyLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/CustomRequestLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/EventHubsDependencyLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/EventHubsRequestLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/EventLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/HttpDependencyLoggingTests.cs, src/Arcus.Observability.Tests.Unit/Telemetry/Logging/HttpRequestLoggingTests.cs
Fixes the second set of telemetry extensions w/ a telemetry context that does not alter the original passed-in context. Split in two parts as there are a lot of extensions/tests to be changed.
Relates to #545
=> fix: do not alter telemetry ctx pt.2

README.md
The `README.md` file was pointing to the wrong Azure DevOps build definition pipeline. Is now fixed. 👍
=> chore: correct build definition ID in readme

src/Arcus.Observability.Telemetry.Core/MessageFormats.cs
Remove the obsolete message formats.
Closes #396
=> chore: remove obsolete message formats

build/ci-build.yml, build/nuget-release.yml, build/templates/run-docker-integration-tests.yml, build/variables/build.yml
Prepare the YAML pipelines to not include a preview .NET version anymore, since there is a new major version for .NET 8 available now.
=> chore: prepare yaml pipelines for .net 8 w/o preview version

src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerAzureKeyVaultDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerAzureSearchDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerBlobStorageDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerCosmosSqlDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerEventHubsDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerEventHubsRequestExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerHttpDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerIotHubDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusRequestExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerSqlDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerTableStorageDependencyExtensions.cs, src/Arcus.Observability.Telemetry.Core/Extensions/ServiceBusEntityType.cs
As defined by discussion #587 , the built-in Microsoft/Azure SDK has evolved to support telemetry natively. This PR therefore deprecates these extensions in the code base so they can be removed in v4.0.
=> chore(deprecate): telemetry extensions for built-in az sdk

src/Arcus.Observability.Telemetry.Core/Iot/IotHubConnectionStringParser.cs, src/Arcus.Observability.Telemetry.Core/Iot/IotHubConnectionStringParserResult.cs, src/Arcus.Observability.Telemetry.Core/Logging/DependencyLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Logging/EventLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Logging/MetricLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Logging/RequestLogEntry.cs, src/Arcus.Observability.Telemetry.Core/Sql/SqlConnectionStringParser.cs, src/Arcus.Observability.Telemetry.Core/Sql/SqlConnectionStringParserResult.cs
In preperation of removing the Guard.NET dependency, we can start replacing usages in the .Core project with the built-in argument checking.
Relates to #577
=> chore(deps): remove guard.net references in core project

src/Arcus.Observability.Correlation/Arcus.Observability.Correlation.csproj, src/Arcus.Observability.Correlation/CorrelationInfo.cs, src/Arcus.Observability.Correlation/CorrelationInfoAccessorProxy.cs, src/Arcus.Observability.Correlation/IServiceCollectionExtensions.cs, src/Arcus.Observability.Tests.Unit/Correlation/CorrelationInfoTests.cs
Removes all Guard.NET references from the .Correlation project in favor of using the built-in argument checking.
Relates to #577
=> chore(deps): remove guard.net references in correlation project

src/Arcus.Observability.Telemetry.Core/Extensions/IReadOnlyDictionaryExtensions.cs, src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LogEventPropertyValueExtensions.cs
The standard .NET SDK already has an extension on dictionaries to provide a default value in case a key/value-pair is missing. We can therefore deprecate/later remove our own version.
Relates to #587
=> chore(core): deprecate unnecessary 'get or default' dic extension
