arcus-azure/arcus.observability

- docs/features/telemetry-enrichment.md
Provide note on NuGet package to install for enrichers.
> Provide note on NuGet package to install for enrichers

- docs/features/writing-different-telemetry-types.md
> Provide documentation for writing metrics

- docs/features/writing-different-telemetry-types.md
> Provide documentation how to track requests

- docs/features/telemetry-enrichment.md
> Provide Kubernetes YAML that shows how to add orchestrator env vars

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Telemetry.Serilog.Enrichers/Extensions/LogEventPropertyValueExtensions.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/ApplicationInsightsTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CloudContextConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CustomTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/Dependencies/HttpDependencyTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/Dependencies/SqlDependencyTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/DependencyTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/EventTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/MetricTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/RequestTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/TraceTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/DependencyType.cs
- src/Arcus.Observability.Tests.Unit/Arcus.Observability.Tests.Unit.csproj
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
Relates to https://github.com/arcus-azure/arcus.observability/issues/22
> Testing - Serilog Application Insights sink conversion

- docs/features/writing-different-telemetry-types.md
- src/Arcus.Observability.Telemetry.Core/DependencyMeasurement.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/DependencyMeasurementTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
Closes https://github.com/arcus-azure/arcus.observability/issues/46
> Feature - introduce 'DependencyMeasurement' for tracking latencies in dependencies

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/ApplicationInsightsSinkTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
> Fix - tracking Application Insights telemetry

- src/Arcus.Observability.Tests.Core/Arcus.Observability.Tests.Core.csproj
- src/Arcus.Observability.Tests.Core/TemporaryEnvironmentVariable.cs
- src/Arcus.Observability.Tests.Integration/Arcus.Observability.Tests.Integration.csproj
- src/Arcus.Observability.Tests.Integration/Serilog/ApplicationInsightsSinkTests.cs
- src/Arcus.Observability.Tests.Unit/Arcus.Observability.Tests.Unit.csproj
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/KubernetesEnricherTests.cs
- src/Arcus.Observability.sln
> Testing - add integration tests for enrichers sinking to Application Insights

- src/Arcus.Observability.Tests.Unit/Serilog/CloudContextConverterTests.cs
> Testing - add unit tests for CloudContextConverter

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/ApplicationInsightsSinkTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
> Feature - log HTTP request/response message

- src/Arcus.Observability.Tests.Integration/Serilog/ApplicationInsightsSinkTests.cs
> Fix - custom dependency tracking on Application Insights

- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CustomTelemetryConverter.cs
> Feature - remove intermediary log properties before forwarding to telemetry

- docs/features/telemetry-enrichment.md
> Fix broken table

- src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj
Be less demanding on NuGet dependency version
> Be less demanding on NuGet dependency version

- docs/features/writing-different-telemetry-types.md
- src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
> Feature - add dependency tracking with SQL connection string

- src/Arcus.Observability.Tests.Integration/Arcus.Observability.Tests.Integration.csproj
- src/Arcus.Observability.Tests.Integration/Serilog/ApplicationInsightsSinkTests.cs
- src/Arcus.Observability.Tests.Integration/appsettings.json
> Testing - add integration tests for Application Insights sink

- docs/features/writing-different-telemetry-types.md
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/ApplicationInsightsSinkTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/XunitLogEventSink.cs
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
> Feature - add Azure Table Storage dependency tracking

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventHubsTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
> Feature - add Azure Event Hubs dependency tracking

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/IoTHubTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
> Feature - add IoT Hub dependency tracking

- src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/CosmosSqlDependencyTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
> Feature - add Cosmos Sql dependency tracking

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/BlobStorageDependencyTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
> Feature - add Azure Blob Container dependency tracking

- docs/features/writing-different-telemetry-types.md
Closes #57 
Closes #56 
Closes #60 
Closes #59
> Docs - complete leftover different type of dependency tracking

- docs/features/writing-different-telemetry-types.md
> Docs - switch blob dependency data with target name

- docs/features/writing-different-telemetry-types.md
- docs/preview/features/writing-different-telemetry-types.md
> Docs - provide section on tracking dependency failures in preview & published docs

- docs/preview/guidance/use-with-dotnet-and-functions.md
- docs/preview/index.md
Provide guidance on configuring Serilog and how it impacts .NET Core & Azure Functions.
Relates to #118
> Provide guidance on configuring Serilog and how it impacts .NET Core & Azure Functions

- docs/preview/features/sinks/azure-application-insights.md
> Provide note how to use an optional instrumentation key

- docs/features/making-telemetry-more-powerful.md
- docs/preview/features/making-telemetry-more-powerful.md
- docs/v0.2.0/features/making-telemetry-more-powerful.md
- docs/v0.3/features/making-telemetry-more-powerful.md
> Fix broken image link

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/RequestTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
Provide capability to only specifiy status code for LogRequest instead of full response.
> Provide capability to only specifiy status code for LogRequest instead of full response

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Telemetry.Core/MessageFormats.cs
> Fix - use TelemetryContext for custom events

- .github/config.yml
Provide issue template configuration to include GitHub Discussions.
> Provide issue template configuration

- src/Arcus.Observability.Telemetry.Serilog.Filters/TelemetryTypeFilter.cs
- src/Arcus.Observability.Tests.Integration/Serilog/TelemetryTypeFilterTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/TelemetryTypeFilterTests.cs
Telemetry type filter should filter out, not in, to align with Serilog's approach.
Fixes #222
> feat: Telemetry type filter should filter out, not in

- src/Arcus.Observability.Telemetry.Serilog.Filters/TelemetryTypeFilter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/DependencyTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/EventTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/MetricTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/RequestTelemetryConverter.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/AzureKeyVaultDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/AzureSearchDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/BlobStorageDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/CosmosSqlDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/CustomDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventHubsTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/HttpDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/IoTHubTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/MetricTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/RequestTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ServiceBusDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/SqlDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/TableStorageDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/TraceTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/TelemetryTypeFilterTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/TelemetryTypeFilterTests.cs
- Alter integration tests to check for properties on the logEvent
> fix: keep properties on the logEvent

- docs/docusaurus.config.js
> docs: Provide link to arcus-azure.net

- src/Arcus.Observability.Tests.Unit/Extensions/TestLoggerExtensions.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/ILoggerExtensionsTests.cs
Improvement on the current rather 'loose' assertion. This improvement will make testing easier to understand and more strict.
Relates to #231
> test: strongly-typed metric assertion in unit tests

- .github/renovate.json
Don't make separate PR's for separate majors.
> fix: renovate don't split multiple majors

- docs/preview/01-index.md
- docs/preview/02-Features/correlation.md
- docs/versioned_docs/version-v0.1.0/01-index.md
- docs/versioned_docs/version-v0.1.0/02-Features/correlation.md
- docs/versioned_docs/version-v0.1.1/01-index.md
- docs/versioned_docs/version-v0.1.1/02-Features/correlation.md
- docs/versioned_docs/version-v0.2.0/01-index.md
- docs/versioned_docs/version-v0.2.0/02-Features/correlation.md
- docs/versioned_docs/version-v0.3/01-index.md
- docs/versioned_docs/version-v0.3/02-Features/correlation.md
- docs/versioned_docs/version-v0.4/01-index.md
- docs/versioned_docs/version-v0.4/02-Features/correlation.md
- docs/versioned_docs/version-v1.0/01-index.md
- docs/versioned_docs/version-v1.0/02-Features/correlation.md
- docs/versioned_docs/version-v2.0/01-index.md
- docs/versioned_docs/version-v2.0/02-Features/correlation.md
- docs/versioned_docs/version-v2.1/01-index.md
- docs/versioned_docs/version-v2.1/02-Features/correlation.md
- docs/versioned_docs/version-v2.2/01-index.md
- docs/versioned_docs/version-v2.2/02-Features/correlation.md
- docs/versioned_docs/version-v2.3/01-index.md
- docs/versioned_docs/version-v2.3/02-Features/correlation.md
Follow-up PR for #338 where we discovered some typo's in the feature docs.
Closes #339
> docs: add follow-up small improvements #338

- src/Arcus.Observability.Correlation/Arcus.Observability.Correlation.csproj
- src/Arcus.Observability.Telemetry.AspNetCore/Arcus.Observability.Telemetry.AspNetCore.csproj
- src/Arcus.Observability.Telemetry.AzureFunctions/Arcus.Observability.Telemetry.AzureFunctions.csproj
- src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj
- src/Arcus.Observability.Telemetry.IoT/Arcus.Observability.Telemetry.IoT.csproj
- src/Arcus.Observability.Telemetry.Serilog.Enrichers/Arcus.Observability.Telemetry.Serilog.Enrichers.csproj
- src/Arcus.Observability.Telemetry.Serilog.Filters/Arcus.Observability.Telemetry.Serilog.Filters.csproj
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights.csproj
- src/Arcus.Observability.Telemetry.Sql/Arcus.Observability.Telemetry.Sql.csproj
Treat warnings as errors.
Relates to https://github.com/arcus-azure/arcus/issues/196
> chore: treat warnings as errors

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureServiceBusDependencyLoggingTests.cs
Adds dependency ID to the Azure Service Bus topic subscription tracking.
> feat: add dependencyid to az servicebus topic dep tracking

- build/nuget-release.yml
Update the release notes header with NuGet installation example.
Relates to https://github.com/arcus-azure/arcus/issues/198
> chore: update release notes header with example

- build/nuget-release.yml
Make sure we have to correct package name in the release notes.
Relates to https://github.com/arcus-azure/arcus/issues/198
> chore: fix correct release notes package name

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerBlobStorageDependencyExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/BlobStorageDependencyTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureBlobStorageDependencyLoggingTests.cs
Adds dependency ID to Azure Blob storage dependency tracking.
> feat: add dependency id to az blob storage dep tracking

- src/Arcus.Observability.Telemetry.AspNetCore/Extensions/ILoggerHttpDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.AspNetCore/Extensions/ILoggerRequestExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/HttpDependencyTests.cs
- src/Arcus.Observability.Tests.Unit/Extensions/TestLoggerExtensions.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/Logging/HttpDependencyLoggingTests.cs
Adds a dependency ID to HTTP dependency tracking.
> feat: add dependency id to http dep tracking

- docs/preview/02-Features/writing-different-telemetry-types.md
Improves the metric logging feature docs with a better description of a metric.
Closes #281
> docs: update w better metric value

- src/Arcus.Observability.Telemetry.AspNetCore/Extensions/ILoggerHttpDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.AspNetCore/Extensions/ILoggerRequestExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerAzureKeyVaultDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerAzureSearchDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerBlobStorageDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerCustomDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerHttpDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerIotHubDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerRequestExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusRequestExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerSqlDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerTableStorageDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.IoT/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Telemetry.Sql/Extensions/ILoggerExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/IoTHubTests.cs
- src/Arcus.Observability.Tests.Runtimes.AzureFunction/local.settings.json
- src/Arcus.Observability.Tests.Unit/Telemetry/Logging/IoTHubDependencyLoggingTests.cs
Adds dependency ID to Azure IoT Hub dependency tracking.
> feat: add dependency id to iot hub dep tracking

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerEventHubsDependencyExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerHttpDependencyExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventHubsTests.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/Logging/EventHubsDependencyLoggingTests.cs
Adds dependency ID to Azure EventHubs dependency tracking.
> feat: add dependency id to event hubs dep tracking

- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerServiceBusDependencyExtensions.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ServiceBusDependencyTests.cs
- src/Arcus.Observability.Tests.Unit/Extensions/TestLoggerExtensions.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/Logging/AzureServiceBusDependencyLoggingTests.cs
Adds Azure Service Bus namespace endpoint to the dependency tracking.
Closes #384
> feat: add az servicebus namespace endpoint to dep tracking

- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/ApplicationInsightsTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/CustomTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/DependencyTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/EventTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/ExceptionTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/MetricTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/OperationContextConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/RequestTelemetryConverter.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/TraceTelemetryConverter.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ApplicationInsightsSinkTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/AzureFunctionsDockerTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ExceptionTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/HttpDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/RequestTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ServiceBusDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/ServiceBusRequestTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/ApplicationInsightsTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/CustomTelemetryConverterTests.cs
- src/Arcus.Observability.Tests.Unit/Serilog/OperationContextConverterTests.cs
Differentiate between request and other types of telemetry tracking.
Closes #410
> feat: diff request & other correlation assignments

- docs/preview/03-Features/writing-different-telemetry-types.md
- src/Arcus.Observability.Telemetry.Core/ContextProperties.cs
- src/Arcus.Observability.Telemetry.Core/Extensions/ILoggerEventHubsRequestExtensions.cs
- src/Arcus.Observability.Telemetry.Core/Logging/RequestLogEntry.cs
- src/Arcus.Observability.Telemetry.Core/Logging/RequestSourceSystem.cs
- src/Arcus.Observability.Telemetry.Serilog.Sinks.ApplicationInsights/Converters/RequestTelemetryConverter.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventHubsDependencyTests.cs
- src/Arcus.Observability.Tests.Integration/Serilog/Sinks/ApplicationInsights/EventHubsRequestTests.cs
- src/Arcus.Observability.Tests.Unit/Extensions/TestLoggerExtensions.cs
- src/Arcus.Observability.Tests.Unit/Telemetry/Logging/EventHubsRequestLoggingTests.cs
Adds request tracking for Azure EventHubs.
Closes #437
> feat: add eventhubs request tracking

- docs/preview/02-Guidance/use-with-dotnet-and-aspnetcore.md
Improve the ASP.NET Core user guide to configure the Arcus Serilog Application Insights sink with the Arcus secret store that retrieves the connection string.
> docs: appinsights secret store connectionstring in aspnetcore userguide

- docs/preview/02-Guidance/use-with-dotnet-and-aspnetcore.md
- docs/preview/02-Guidance/use-with-dotnet-and-functions.md
Improve the user guide to setup the Arcus Application Insights Serilog sink.
> docs: improve appinsights user guide w/ az func

- docs/preview/03-Features/telemetry-filter.md
Add an example sentence on how to use the telemetry filters.
Closes #420
> docs: improve telemetry filter feature docs

- docs/preview/01-index.md
- docs/versioned_docs/version-v2.6.0/01-index.md
Corrects introduction based on component description.
Relates to https://github.com/arcus-azure/arcus/pull/278
> docs: correct introduction

- .github/workflows/code-coverage.yml
- README.md
- src/Arcus.Observability.Tests.Unit/Arcus.Observability.Tests.Unit.csproj
Add code coverage reporting.
Relates to https://github.com/arcus-azure/arcus/issues/264
> chore: add code coverage

- src/Arcus.Observability.Correlation/Arcus.Observability.Correlation.csproj
- src/Arcus.Observability.Telemetry.AspNetCore/Arcus.Observability.Telemetry.AspNetCore.csproj
- src/Arcus.Observability.Telemetry.AzureFunctions/Arcus.Observability.Telemetry.AzureFunctions.csproj
- src/Arcus.Observability.Telemetry.Core/Arcus.Observability.Telemetry.Core.csproj
- src/Arcus.Observability.Telemetry.IoT/Arcus.Observability.Telemetry.IoT.csproj
- src/Arcus.Observability.Telemetry.Serilog.Enrichers/Arcus.Observability.Telemetry.Serilog.Enrichers.csproj
- src/Arcus.Observability.Telemetry.Serilog.Filters/Arcus.Observability.Telemetry.Serilog.Filters.csproj
Simplify NuGet package resolving by removing any .NET Core related conditions.
> chore: simplify net8.0 package resolve
